// inline-buy-1.0-all.js for staging
//
// Points Inline Buy Library (c) Copyright Points International Ltd. 2012. All Rights Reserved
// Underscore.js 1.3.1
// (c) 2009-2012 Jeremy Ashkenas, DocumentCloud Inc.
// Underscore is freely distributable under the MIT license.
// Portions of Underscore are inspired or borrowed from Prototype,
// Oliver Steele's Functional, and John Resig's Micro-Templating.
// For all details and documentation:
// http://documentcloud.github.com/underscore
// TinyBox2
// (c) Commons Creative License
(function(q,O){(function(){function g(a,f,m){if(a===f)return 0!==a||1/a==1/f;if(null==a||null==f)return a===f;a._chain&&(a=a._wrapped);f._chain&&(f=f._wrapped);if(a.isEqual&&b.isFunction(a.isEqual))return a.isEqual(f);if(f.isEqual&&b.isFunction(f.isEqual))return f.isEqual(a);var p=n.call(a);if(p!=n.call(f))return!1;switch(p){case "[object String]":return a==String(f);case "[object Number]":return a!=+a?f!=+f:0==a?1/a==1/f:a==+f;case "[object Date]":case "[object Boolean]":return+a==+f;case "[object RegExp]":return a.source==
f.source&&a.global==f.global&&a.multiline==f.multiline&&a.ignoreCase==f.ignoreCase}if("object"!=typeof a||"object"!=typeof f)return!1;for(var c=m.length;c--;)if(m[c]==a)return!0;m.push(a);var c=0,d=!0;if("[object Array]"==p){if(c=a.length,d=c==f.length)for(;c--&&(d=c in a==c in f&&g(a[c],f[c],m)););}else{if("constructor"in a!="constructor"in f||a.constructor!=f.constructor)return!1;for(var e in a)if(b.has(a,e)&&(c++,!(d=b.has(f,e)&&g(a[e],f[e],m))))break;if(d){for(e in f)if(b.has(f,e)&&!c--)break;
d=!c}}m.pop();return d}var h=this,e=h._,l={},d=Array.prototype,k=Object.prototype,c=d.slice,J=d.unshift,n=k.toString,B=k.hasOwnProperty,w=d.forEach,u=d.map,t=d.reduce,q=d.reduceRight,D=d.filter,H=d.every,E=d.some,y=d.indexOf,F=d.lastIndexOf,k=Array.isArray,z=Object.keys,x=Function.prototype.bind,b=function(a){return new A(a)};"undefined"!==typeof exports?("undefined"!==typeof module&&module.exports&&(exports=module.exports=b),exports._=b):h._=b;b.VERSION="1.3.1";var r=b.each=b.forEach=function(a,
f,m){if(null!=a)if(w&&a.forEach===w)a.forEach(f,m);else if(a.length===+a.length)for(var p=0,c=a.length;p<c&&!(p in a&&f.call(m,a[p],p,a)===l);p++);else for(p in a)if(b.has(a,p)&&f.call(m,a[p],p,a)===l)break};b.map=b.collect=function(a,f,b){var p=[];if(null==a)return p;if(u&&a.map===u)return a.map(f,b);r(a,function(a,c,d){p[p.length]=f.call(b,a,c,d)});a.length===+a.length&&(p.length=a.length);return p};b.reduce=b.foldl=b.inject=function(a,f,m,p){var c=2<arguments.length;null==a&&(a=[]);if(t&&a.reduce===
t)return p&&(f=b.bind(f,p)),c?a.reduce(f,m):a.reduce(f);r(a,function(a,b,d){c?m=f.call(p,m,a,b,d):(m=a,c=!0)});if(!c)throw new TypeError("Reduce of empty array with no initial value");return m};b.reduceRight=b.foldr=function(a,f,m,p){var c=2<arguments.length;null==a&&(a=[]);if(q&&a.reduceRight===q)return p&&(f=b.bind(f,p)),c?a.reduceRight(f,m):a.reduceRight(f);var d=b.toArray(a).reverse();p&&!c&&(f=b.bind(f,p));return c?b.reduce(d,f,m,p):b.reduce(d,f)};b.find=b.detect=function(a,f,b){var p;I(a,function(a,
c,d){if(f.call(b,a,c,d))return p=a,!0});return p};b.filter=b.select=function(a,f,b){var p=[];if(null==a)return p;if(D&&a.filter===D)return a.filter(f,b);r(a,function(a,c,d){f.call(b,a,c,d)&&(p[p.length]=a)});return p};b.reject=function(a,f,b){var p=[];if(null==a)return p;r(a,function(a,c,d){f.call(b,a,c,d)||(p[p.length]=a)});return p};b.every=b.all=function(a,f,b){var p=!0;if(null==a)return p;if(H&&a.every===H)return a.every(f,b);r(a,function(a,c,d){if(!(p=p&&f.call(b,a,c,d)))return l});return p};
var I=b.some=b.any=function(a,f,m){f||(f=b.identity);var p=!1;if(null==a)return p;if(E&&a.some===E)return a.some(f,m);r(a,function(a,b,c){if(p||(p=f.call(m,a,b,c)))return l});return!!p};b.include=b.contains=function(a,f){return null==a?!1:y&&a.indexOf===y?-1!=a.indexOf(f):I(a,function(a){return a===f})};b.invoke=function(a,f){var m=c.call(arguments,2);return b.map(a,function(a){return(b.isFunction(f)?f||a:a[f]).apply(a,m)})};b.pluck=function(a,f){return b.map(a,function(a){return a[f]})};b.max=function(a,
f,m){if(!f&&b.isArray(a))return Math.max.apply(Math,a);if(!f&&b.isEmpty(a))return-Infinity;var c={computed:-Infinity};r(a,function(a,b,d){b=f?f.call(m,a,b,d):a;b>=c.computed&&(c={value:a,computed:b})});return c.value};b.min=function(a,f,m){if(!f&&b.isArray(a))return Math.min.apply(Math,a);if(!f&&b.isEmpty(a))return Infinity;var c={computed:Infinity};r(a,function(a,b,d){b=f?f.call(m,a,b,d):a;b<c.computed&&(c={value:a,computed:b})});return c.value};b.shuffle=function(a){var f=[],b;r(a,function(a,c){0==
c?f[0]=a:(b=Math.floor(Math.random()*(c+1)),f[c]=f[b],f[b]=a)});return f};b.sortBy=function(a,f,m){return b.pluck(b.map(a,function(a,b,c){return{value:a,criteria:f.call(m,a,b,c)}}).sort(function(a,b){var f=a.criteria,m=b.criteria;return f<m?-1:f>m?1:0}),"value")};b.groupBy=function(a,f){var m={},c=b.isFunction(f)?f:function(a){return a[f]};r(a,function(a,f){var b=c(a,f);(m[b]||(m[b]=[])).push(a)});return m};b.sortedIndex=function(a,f,m){m||(m=b.identity);for(var c=0,d=a.length;c<d;){var e=c+d>>1;
m(a[e])<m(f)?c=e+1:d=e}return c};b.toArray=function(a){return!a?[]:a.toArray?a.toArray():b.isArray(a)?c.call(a):b.isArguments(a)?c.call(a):b.values(a)};b.size=function(a){return b.toArray(a).length};b.first=b.head=function(a,b,m){return null!=b&&!m?c.call(a,0,b):a[0]};b.initial=function(a,b,m){return c.call(a,0,a.length-(null==b||m?1:b))};b.last=function(a,b,m){return null!=b&&!m?c.call(a,Math.max(a.length-b,0)):a[a.length-1]};b.rest=b.tail=function(a,b,m){return c.call(a,null==b||m?1:b)};b.compact=
function(a){return b.filter(a,function(a){return!!a})};b.flatten=function(a,f){return b.reduce(a,function(a,c){if(b.isArray(c))return a.concat(f?c:b.flatten(c));a[a.length]=c;return a},[])};b.without=function(a){return b.difference(a,c.call(arguments,1))};b.uniq=b.unique=function(a,f,c){c=c?b.map(a,c):a;var d=[];b.reduce(c,function(c,m,e){if(0==e||(!0===f?b.last(c)!=m:!b.include(c,m)))c[c.length]=m,d[d.length]=a[e];return c},[]);return d};b.union=function(){return b.uniq(b.flatten(arguments,!0))};
b.intersection=b.intersect=function(a){var f=c.call(arguments,1);return b.filter(b.uniq(a),function(a){return b.every(f,function(f){return 0<=b.indexOf(f,a)})})};b.difference=function(a){var f=b.flatten(c.call(arguments,1));return b.filter(a,function(a){return!b.include(f,a)})};b.zip=function(){for(var a=c.call(arguments),f=b.max(b.pluck(a,"length")),m=Array(f),d=0;d<f;d++)m[d]=b.pluck(a,""+d);return m};b.indexOf=function(a,f,c){if(null==a)return-1;var d;if(c)return c=b.sortedIndex(a,f),a[c]===f?
c:-1;if(y&&a.indexOf===y)return a.indexOf(f);c=0;for(d=a.length;c<d;c++)if(c in a&&a[c]===f)return c;return-1};b.lastIndexOf=function(a,b){if(null==a)return-1;if(F&&a.lastIndexOf===F)return a.lastIndexOf(b);for(var c=a.length;c--;)if(c in a&&a[c]===b)return c;return-1};b.range=function(a,b,c){1>=arguments.length&&(b=a||0,a=0);c=arguments[2]||1;for(var d=Math.max(Math.ceil((b-a)/c),0),e=0,n=Array(d);e<d;)n[e++]=a,a+=c;return n};var G=function(){};b.bind=function(a,f){var d,e;if(a.bind===x&&x)return x.apply(a,
c.call(arguments,1));if(!b.isFunction(a))throw new TypeError;e=c.call(arguments,2);return d=function(){if(!(this instanceof d))return a.apply(f,e.concat(c.call(arguments)));G.prototype=a.prototype;var b=new G,n=a.apply(b,e.concat(c.call(arguments)));return Object(n)===n?n:b}};b.bindAll=function(a){var f=c.call(arguments,1);0==f.length&&(f=b.functions(a));r(f,function(f){a[f]=b.bind(a[f],a)});return a};b.memoize=function(a,f){var c={};f||(f=b.identity);return function(){var d=f.apply(this,arguments);
return b.has(c,d)?c[d]:c[d]=a.apply(this,arguments)}};b.delay=function(a,b){var d=c.call(arguments,2);return setTimeout(function(){return a.apply(a,d)},b)};b.defer=function(a){return b.delay.apply(b,[a,1].concat(c.call(arguments,1)))};b.throttle=function(a,f){var c,d,e,n,g,h=b.debounce(function(){g=n=!1},f);return function(){c=this;d=arguments;e||(e=setTimeout(function(){e=null;g&&a.apply(c,d);h()},f));n?g=!0:a.apply(c,d);h();n=!0}};b.debounce=function(a,b){var c;return function(){var d=this,e=arguments;
clearTimeout(c);c=setTimeout(function(){c=null;a.apply(d,e)},b)}};b.once=function(a){var b=!1,c;return function(){if(b)return c;b=!0;return c=a.apply(this,arguments)}};b.wrap=function(a,b){return function(){var d=[a].concat(c.call(arguments,0));return b.apply(this,d)}};b.compose=function(){var a=arguments;return function(){for(var b=arguments,c=a.length-1;0<=c;c--)b=[a[c].apply(this,b)];return b[0]}};b.after=function(a,b){return 0>=a?b():function(){if(1>--a)return b.apply(this,arguments)}};b.keys=
z||function(a){if(a!==Object(a))throw new TypeError("Invalid object");var c=[],d;for(d in a)b.has(a,d)&&(c[c.length]=d);return c};b.values=function(a){return b.map(a,b.identity)};b.functions=b.methods=function(a){var c=[],d;for(d in a)b.isFunction(a[d])&&c.push(d);return c.sort()};b.extend=function(a){r(c.call(arguments,1),function(b){for(var c in b)a[c]=b[c]});return a};b.defaults=function(a){r(c.call(arguments,1),function(b){for(var c in b)null==a[c]&&(a[c]=b[c])});return a};b.clone=function(a){return!b.isObject(a)?
a:b.isArray(a)?a.slice():b.extend({},a)};b.tap=function(a,b){b(a);return a};b.isEqual=function(a,b){return g(a,b,[])};b.isEmpty=function(a){if(b.isArray(a)||b.isString(a))return 0===a.length;for(var c in a)if(b.has(a,c))return!1;return!0};b.isElement=function(a){return!!(a&&1==a.nodeType)};b.isArray=k||function(a){return"[object Array]"==n.call(a)};b.isObject=function(a){return a===Object(a)};b.isArguments=function(a){return"[object Arguments]"==n.call(a)};b.isArguments(arguments)||(b.isArguments=
function(a){return!(!a||!b.has(a,"callee"))});b.isFunction=function(a){return"[object Function]"==n.call(a)};b.isString=function(a){return"[object String]"==n.call(a)};b.isNumber=function(a){return"[object Number]"==n.call(a)};b.isNaN=function(a){return a!==a};b.isBoolean=function(a){return!0===a||!1===a||"[object Boolean]"==n.call(a)};b.isDate=function(a){return"[object Date]"==n.call(a)};b.isRegExp=function(a){return"[object RegExp]"==n.call(a)};b.isNull=function(a){return null===a};b.isUndefined=
function(a){return void 0===a};b.has=function(a,b){return B.call(a,b)};b.noConflict=function(){h._=e;return this};b.identity=function(a){return a};b.times=function(a,b,c){for(var d=0;d<a;d++)b.call(c,d)};b.escape=function(a){return(""+a).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#x27;").replace(/\//g,"&#x2F;")};b.mixin=function(a){r(b.functions(a),function(c){N(c,b[c]=a[c])})};var C=0;b.uniqueId=function(a){var b=C++;return a?a+b:b};b.templateSettings=
{evaluate:/<%([\s\S]+?)%>/g,interpolate:/<%=([\s\S]+?)%>/g,escape:/<%-([\s\S]+?)%>/g};var K=/.^/,L=function(a){return a.replace(/\\\\/g,"\\").replace(/\\'/g,"'")};b.template=function(a,c){var d=b.templateSettings,d="var __p=[],print=function(){__p.push.apply(__p,arguments);};with(obj||{}){__p.push('"+a.replace(/\\/g,"\\\\").replace(/'/g,"\\'").replace(d.escape||K,function(a,b){return"',_.escape("+L(b)+"),'"}).replace(d.interpolate||K,function(a,b){return"',"+L(b)+",'"}).replace(d.evaluate||K,function(a,
b){return"');"+L(b).replace(/[\r\n\t]/g," ")+";__p.push('"}).replace(/\r/g,"\\r").replace(/\n/g,"\\n").replace(/\t/g,"\\t")+"');}return __p.join('');",e=new Function("obj","_",d);return c?e(c,b):function(a){return e.call(this,a,b)}};b.chain=function(a){return b(a).chain()};var A=function(a){this._wrapped=a};b.prototype=A.prototype;var M=function(a,c){return c?b(a).chain():a},N=function(a,d){A.prototype[a]=function(){var a=c.call(arguments);J.call(a,this._wrapped);return M(d.apply(b,a),this._chain)}};
b.mixin(b);r("pop push reverse shift sort splice unshift".split(" "),function(a){var b=d[a];A.prototype[a]=function(){var c=this._wrapped;b.apply(c,arguments);var d=c.length;("shift"==a||"splice"==a)&&0===d&&delete c[0];return M(c,this._chain)}});r(["concat","join","slice"],function(a){var b=d[a];A.prototype[a]=function(){return M(b.apply(this._wrapped,arguments),this._chain)}});A.prototype.chain=function(){this._chain=!0;return this};A.prototype.value=function(){return this._wrapped}}).call(this);
TINY={};TINY.box=function(){var g,h,e,l,d,k=0;return{show:function(c){d={opacity:70,close:1,animate:1,fixed:1,mask:1,maskid:"",boxid:"",topsplit:2,url:0,post:0,height:0,width:0,html:0,iframe:0};for(s in c)d[s]=c[s];k?(g.style.display="none",clearTimeout(k.ah),l.v&&(k.removeChild(l),l.v=0)):(g=document.createElement("div"),g.className="tbox",k=document.createElement("div"),k.className="tinner",e=document.createElement("div"),e.className="tcontent",h=document.createElement("div"),h.className="tmask",
l=document.createElement("div"),l.className="tclose",l.v=0,document.body.appendChild(h),document.body.appendChild(g),g.appendChild(k),k.appendChild(e),h.onclick=l.onclick=TINY.box.hide,q.onresize=TINY.box.resize);k.id=d.boxid;h.id=d.maskid;g.style.position=d.fixed?"fixed":"absolute";d.html&&!d.animate?(k.style.backgroundImage="none",e.innerHTML=d.html,e.style.display="",k.style.width=d.width?d.width+"px":"auto",k.style.height=d.height?d.height+"px":"auto"):(e.style.display="none",!d.animate&&d.width&&
d.height?(k.style.width=d.width+"px",k.style.height=d.height+"px"):k.style.width=k.style.height="100px");d.mask?(this.mask(),this.alpha(h,1,d.opacity)):this.alpha(g,1,100);d.autohide?k.ah=setTimeout(TINY.box.hide,1E3*d.autohide):document.onkeyup=TINY.box.esc},fill:function(c,e,n,g,h,l){if(e)if(d.image){var t=new Image;t.onload=function(){h=h||t.width;l=l||t.height;TINY.box.psh(t,g,h,l)};t.src=d.image}else if(d.iframe)this.psh('<iframe src="'+d.iframe+'" width="'+d.width+'" frameborder="0" height="'+
d.height+'"></iframe>',g,h,l);else{var v=q.XMLHttpRequest?new XMLHttpRequest:new ActiveXObject("Microsoft.XMLHTTP");v.onreadystatechange=function(){4==v.readyState&&200==v.status&&(k.style.backgroundImage="",TINY.box.psh(v.responseText,g,h,l))};n?(v.open("POST",c,!0),v.setRequestHeader("Content-type","application/x-www-form-urlencoded"),v.send(n)):(v.open("GET",c,!0),v.send(null))}else this.psh(c,g,h,l)},psh:function(c,d,n,h){"object"==typeof c?e.appendChild(c):e.innerHTML=c;c=k.style.width;var g=
k.style.height;if(!n||!h)k.style.width=n?n+"px":"",k.style.height=h?h+"px":"",e.style.display="",h||(h=parseInt(e.offsetHeight)),n||(n=parseInt(e.offsetWidth)),e.style.display="none";k.style.width=c;k.style.height=g;this.size(n,h,d)},esc:function(c){c=c||q.event;27==c.keyCode&&TINY.box.hide()},hide:function(){TINY.box.alpha(g,-1,0,3);document.onkeypress=null;d.closejs&&d.closejs()},resize:function(){TINY.box.pos();TINY.box.mask()},mask:function(){h.style.height=this.total(1)+"px";h.style.width=this.total(0)+
"px"},pos:function(){var c;"undefined"!=typeof d.top?c=d.top:(c=this.height()/d.topsplit-g.offsetHeight/2,c=20>c?20:c);!d.fixed&&!d.top&&(c+=this.top());g.style.top=c+"px";g.style.left="undefined"!=typeof d.left?d.left+"px":this.width()/2-g.offsetWidth/2+"px"},alpha:function(c,d,e){clearInterval(c.ai);d&&(c.style.opacity=0,c.style.filter="alpha(opacity=0)",c.style.display="block",TINY.box.pos());c.ai=setInterval(function(){TINY.box.ta(c,e,d)},20)},ta:function(c,l,n){var B=Math.round(100*c.style.opacity);
B==l?(clearInterval(c.ai),-1==n?(c.style.display="none",c==g?TINY.box.alpha(h,-1,0,2):e.innerHTML=k.style.backgroundImage=""):c==h?this.alpha(g,1,100):(g.style.filter="",TINY.box.fill(d.html||d.url,d.url||d.iframe||d.image,d.post,d.animate,d.width,d.height))):(l-=Math.floor(0.5*Math.abs(l-B))*n,c.style.opacity=l/100,c.style.filter="alpha(opacity="+l+")")},size:function(c,h,n){if(n){clearInterval(k.si);var g=parseInt(k.style.width)>c?-1:1,w=parseInt(k.style.height)>h?-1:1;k.si=setInterval(function(){TINY.box.ts(c,
g,h,w)},20)}else k.style.backgroundImage="none",d.close&&(k.appendChild(l),l.v=1),k.style.width=c+"px",k.style.height=h+"px",e.style.display="",this.pos(),d.openjs&&d.openjs()},ts:function(c,h,n,g){var w=parseInt(k.style.width),u=parseInt(k.style.height);w==c&&u==n?(clearInterval(k.si),k.style.backgroundImage="none",e.style.display="block",d.close&&(k.appendChild(l),l.v=1),d.openjs&&d.openjs()):(w!=c&&(k.style.width=c-Math.floor(0.6*Math.abs(c-w))*h+"px"),u!=n&&(k.style.height=n-Math.floor(0.6*Math.abs(n-
u))*g+"px"),this.pos())},top:function(){return document.documentElement.scrollTop||document.body.scrollTop},width:function(){return self.innerWidth||document.documentElement.clientWidth||document.body.clientWidth},height:function(){return self.innerHeight||document.documentElement.clientHeight||document.body.clientHeight},total:function(c){var d=document.body,e=document.documentElement;return c?Math.max(Math.max(d.scrollHeight,e.scrollHeight),Math.max(d.clientHeight,e.clientHeight)):Math.max(Math.max(d.scrollWidth,
e.scrollWidth),Math.max(d.clientWidth,e.clientWidth))}}}();(function(){function g(h,e,l){var d=/\[\]$/;if(_.isArray(e))_.each(e,function(c,e){d.test(h)?l(h,e):g(h+"["+("object"===typeof e||_.isArray(e)?c:"")+"]",e,l)});else if(null!==e&&"object"===typeof e)for(var k in e)g(h+"["+k+"]",e[k],l);else l(h,e)}_.mixin({nullify:function(h){_.each(_.toArray(arguments).slice(1),function(e,g,d){for(var k in e)delete h[e[k]]});return h},param:function(h){var e=[],l=function(d,c){c=_.isFunction(c)?c():c;e[e.length]=
encodeURIComponent(d)+"="+encodeURIComponent(c)};if(_.isArray(h))_.each(h,function(){l(this.name,this.value)});else for(var d in h)g(d,h[d],l);return e.join("&").replace(/%20/g,"+")},isWindow:function(h){return h&&"object"===typeof h&&"setInterval"in h},randomInt:function(h,e){return Math.floor(Math.random()*(e-h+1))+h},getViewportHeight:function(){return q.innerHeight||document.documentElement.clientHeight||document.getElementsByTagName("body")[0].clientHeight},compiled:function(h){_.templateSettings=
{interpolate:/<%=([\s\S]+?)%>/g};return _.template(h)(q.APP_CONFIG||{})},getChildByClassName:function(h,e){var g=document.getElementById(h),d,k;g&&(d=g.childNodes);g=0;for(k=d.length;g<k;g++){var c=d[g];if(-1<c.className.indexOf(e))return c}return null}})})();PTS=q.PTS||{};PTS.namespace=function(g){g=g.split(".");var h=PTS;"PTS"===g[0]&&(g=g.slice(1));for(var e=0;e<g.length;e++)"undefined"===typeof h[g[e]]&&(h[g[e]]={}),h=h[g[e]];return h};PTS.JsonpFetcher=function(g,h,e){var l=0,d,k,c;e={};var q,
n;q=function(c,e){var g=h.createElement("script"),n=!1;g.src=c;g.async=!0;g.onerror=function(){e&&e()};g.onload=g.onreadystatechange=function(){if(!n&&(!this.readyState||"loaded"===this.readyState||"complete"===this.readyState))n=!0,g.onload=g.onreadystatechange=null,g&&g.parentNode&&g.parentNode.removeChild(g)};d||(d=h.getElementsByTagName("head")[0]);d.appendChild(g)};e.get=function(d,e,h,t){k="?";e=e||{};for(c in e)e.hasOwnProperty(c)&&(k+=encodeURIComponent(c)+"="+encodeURIComponent(e[c])+"&");
n="pts_json"+ ++l;g[n]=function(c){h(c);try{delete g[n]}catch(d){}g[n]=null};q(d+k+"callback="+n,t);return n};return e}(q,document);PTS.namespace("PTS.logging");PTS.logging.Logger=function(g){_.isNull(g)&&(g="?error={{ message }}");this._logFormat=g};PTS.logging.Logger.prototype.replaceTokens=function(g,h){_.templateSettings={interpolate:/\{\{(.+?)\}\}/g};return _.template(g)(h)};PTS.logging.Logger.prototype.log=function(g,h){var e=this.replaceTokens(this._logFormat,h);q.console&&(console.log(e),
PTS.debugMode&&!_.isUndefined(g)&&console.log(g.stack))};PTS.logging.RemoteLogger=function(g){_.isNull(g)&&(g="?error={{ message }}");this._logFormat=g};PTS.logging.RemoteLogger.prototype=new PTS.logging.Logger;PTS.logging.RemoteLogger.prototype.log=function(g,h){var e;e=this.replaceTokens(this._logFormat,h);PTS.JsonpFetcher.get(e)};PTS.namespace("PTS.analytics");PTS.analytics.EventTracker=function(g,h){if(!_.isString(g)||_.isEmpty(g))throw Error("account as string is required");if(!_.isString(h)||
_.isEmpty(h))throw Error("baseUrl as string is reuired");this._account=g;this._baseUrl=h};PTS.analytics.EventTracker.prototype.getImgUrl=function(g,h){var e,l,d=q.document.referer;l=q.location;e=this._baseUrl+"?";e+="utmac="+this._account;e+="&utmn="+_.randomInt(1E3,1E8);l=l.pathname.substring(1);_.isEmpty(d)&&(d="-");e+="&utmr="+encodeURIComponent(d);_.isEmpty(l)||(e+="&utmp="+encodeURIComponent(l));_.isEmpty(g)||(e+=encodeURIComponent("/"+g));_.isEmpty(h)||(e+="&utme="+encodeURIComponent("8(Language*4!Currency*Partner)9(en*4!USD*"+
h+")11(2*4!2*2)"));return e+"&guid=ON"};PTS.namespace("PTS.errors");PTS.errors.ErrorHandler=function(){var g=function(){};g.prototype={constructor:PTS.errors.ErrorHandler,handleError:function(g,e){g instanceof PTS.errors.ValidationError&&(_.isFunction(e)?e(g):g.visible&&alert("Our system is temporarily unavailable. Please refresh the page and try again, or contact customer service."))}};return g}();PTS.errors.ValidationError=function(g,h){var e=function(e,d){this.message=e||"";this.visible=!!d;this.name=
"ValidationError"};e.prototype={constr:PTS.errors.ValidationError};return e}();PTS.errors.ValidationError.prototype=Error();(function(g,h){function e(c){c=c||h;return c.querySelectorAll("a[href], area[href], input:not([disabled]),select:not([disabled]), textarea:not([disabled]),button:not([disabled]), iframe, object, embed, *[tabindex],*[contenteditable]")}function l(c){setTimeout(function(){c.focus()},10)}function d(c){var d=e(h.querySelector(".tbox")),g=d[0],d=d[d.length-1],k=c.which||c.keyCode;
c.preventDefault=c.preventDefault||function(){c.returnValue=!1};k===q&&(c.target===d&&!c.shiftKey?(c.preventDefault(),l(g)):c.target===g&&c.shiftKey&&(c.preventDefault(),l(d)))}function k(c){return c===h?!0:c.hidden||"none"===c.style.display?!1:k(c.parentNode)}function c(c){TINY.box.isOpen&&h.querySelector(".tclose").focus()}TINY.box=TINY.box||{};var q=9;TINY.box.keepFocus=function(){var g=h.querySelector(".tbox"),l=e(),q=e(g);g.addEventListener("keydown",d,!1);g=_.filter(l,function(c){return!_.contains(q,
c)}).reverse();g=_.find(g,function(c){return k(c)});console.log(g);g&&g.addEventListener("focus",c,!1)}})(q,document);PTS.namespace("PTS.inlineBuy");PTS.inlineBuy=function(){var g=q.document,h=TINY.box.hide,e={},l={memberId:"",transactionQuantity:"",memberEmail:"",successUrl:location.href,partnerName:"",firstName:"",lastName:"",accountBalance:"",redemptionQuantity:"",partnerReferenceId:"",product:"buy",closeConfirm:"Are you sure you want to close this dialog?",cssVersion:"1.0"},d=["ssoGatewayUrl",
"loggingBaseUrl","txnStatusUrls","cssUrl"],k=!!_.compiled(""),c=["memberId","partnerName","product"],J="transactionQuantity memberEmail successUrl firstName lastName accountBalance redemptionQuantity partnerReferenceId cssVersion".split(" "),n=new PTS.errors.ErrorHandler,B=new PTS.logging.Logger("{{ message }}"),w=new PTS.logging.RemoteLogger(_.compiled("https://staging.api.points.com/log")+"/bgt/{{ partnerName }}/buy/error/?f={{ filename }}&error={{ message }}&url={{ url }}"),u=function(b){var c,
d;c=_.compiled("MO-15827413-1");d=_.compiled("https://staging.api.points.com/ga/v1/pts.jsp");!_.isEmpty(c)&&!_.isEmpty(d)&&(c=new PTS.analytics.EventTracker(c,d),c=c.getImgUrl(b,l.partnerName),d=g.createElement("img"),d.setAttribute("src",c),d.setAttribute("id","GA_"+b),d.style.display="none",g.getElementsByTagName("body")[0].appendChild(d))},t=function(b){var c;b instanceof Error||(errorMessage=b||"noErrorMessage",b=Error(errorMessage));c=_.compiled("inline-buy-1.0-all.js");w.log(b,{partnerName:l.partnerName||
"noPartnerName",filename:c,message:b.name.toString()+": "+b.message.toString(),url:q.location||"noUrl"});PTS.debugMode&&(msg=_.isArray(b)?b.toString():b,B.log(b,{message:msg}))},v=function(b){var e={},n={externalTxId:[b.partnerName||l.partnerName||"noPartnerName",+new Date,_.randomInt(1E4,1E5)].join("")};_.extend(e,l,b,n);(k||!PTS.debugMode)&&_.nullify(e,d);b=D(e,c);if(!_.isEmpty(b))throw new PTS.errors.ValidationError(b,"visible");b=D(e,J);_.isEmpty(b)||t(new PTS.errors.ValidationError(b));b=e.ssoGatewayUrl||
_.compiled("https://obuat.ssogateway.points.com/SSOGateway/gateway.do");b+=-1==b.indexOf("?")?"?":"&";b+=_.param({accountNumber:e.memberId,transactionQuantity:e.transactionQuantity,email:e.memberEmail,successURL:e.successUrl,ssoSource:e.partnerName,firstName:e.firstName,lastName:e.lastName,balance:e.accountBalance,redemptionQuantity:e.redemptionQuantity,referenceId:e.partnerReferenceId,ssoProduct:e.product,externalTxId:e.externalTxId});TINY.box.esc=function(){};TINY.box.hide=function(b){var c="",
a=function(){if("COMPLETED"===c)""!==e.successUrl?top.location=e.successUrl:top.location.reload();else return u("close/txn-not-completed"),h()},d={ebgt:_.compiled("https://staging.buy.points.com/PointsPartner/service/transaction/status"),bgt3:_.compiled("https://storefront-staging.lxc.points.com/order-status")},g=function(a){a=a.status;"COMPLETED"===a?c=a:"NOT_COMPLETED"===a&&""===c&&(c=a)};_.extend(d,e.txnStatusUrls);if(H(b))if(u("closeclicked"),PTS.JsonpFetcher.get(d.ebgt,{external_transaction_id:e.externalTxId},
g),PTS.JsonpFetcher.get(d.bgt3,{external_transaction_id:e.externalTxId},g),confirm(e.closeConfirm)){if(""!==c)return a();b=_.getChildByClassName("pts-box","tclose");b.className+=" pts-close-waiting";q.setTimeout(function(){if(""!==c)return a();t("transaction status jsonp call never returned");u("close/failed-txn-status");return h()},2E3)}else return u("closecancelled"),!1};TINY.box.show({iframe:b,boxid:"pts-box",maskid:"pts-mask",width:e.boxWidth||750,height:Math.max(Math.floor(_.getViewportHeight())-
(e.boxVerticalMargin||80),400),fixed:!1,maskopacity:40,openjs:function(){var b=g.getElementById("pts-box"),c=g.createElement("span"),a=g.createElement("span"),d=null;c.id="pts-box-label";c.setAttribute("style","display:none");c.innerText="Buy Points Popup Dialog Box";a.id="pts-box-description";a.setAttribute("style","display:none");a.innerText="In this modal window you can top up your account to complete the booking with points.";b.setAttribute("role","dialog");b.setAttribute("aria-labelledby","pts-box-label");
b.setAttribute("aria-describedby","pts-box-description");b.appendChild(c);b.appendChild(a);b.getElementsByTagName("iframe")[0].setAttribute("id","pts-iframe");if(b=_.getChildByClassName("pts-box","tclose"))b.innerHTML='<span aria-hidden="true" class="pts-close-x">\u00d7</span> <span class="pts-close-text">Close</span>',b.style.position="absolute",b.style.top="0",b.style.cursor="pointer",b.style.fontFamily="helvetica,sans-serif",b.style.fontSize="20px",b.setAttribute("tabindex",0),b.setAttribute("role",
"button"),b.focus(),PTS._closeButtonKeyDownHandler=PTS._closeButtonKeyDownHandler||function(a){13===(a.which||a.keyCode)&&TINY.box.hide(a)},b.addEventListener("keydown",PTS._closeButtonKeyDownHandler,!1);d=g.getElementById("pts-iframe");d.setAttribute("title","Buy Points");TINY.box.keepFocus();TINY.box.isOpen=!0},closejs:function(){var b=_.getChildByClassName("pts-box","tclose");b.className=b.className.replace(" pts-close-waiting","");TINY.box.isOpen=!1}})},D=function(b,c){var d=[];_.each(c,function(c){var e=
b[c];(_.isUndefined(e)||_.isNull(e)||_.isString(e)&&0===e.length)&&d.push(c+" is required")});return d},H=function(b){b=b||q.event;return"pts-mask"==(b.target||b.srcElement).id?!1:!0};try{if(_.isUndefined(q.pointsAsyncInit)){var E=Error("Missing window.pointsAsyncInit() function.");n.handleError(E);t(E)}else{var y,F,z=g.createElement("link"),x=g.createElement("style"),b=_.compiled("https://staging.static.points.com/buy"),r=_.compiled("inline.css"),I=_.compiled("style");g.getElementsByTagName("body");
var G=g.getElementsByTagName("head")[0];_.extend(l,q.pointsAsyncInit()||{});(k||!PTS.debugMode)&&_.nullify(l,d);x.setAttribute("type","text/css");y=g.createTextNode(".tbox{position:absolute;display:none;padding:14px 17px;z-index:900}#pts-box{padding:15px;-moz-border-radius:5px;border-radius:5px;background:#fff url(https://staging.static.points.com/buy/default/buy/images/preload.gif) no-repeat 50% 50%;border-right:1px solid #333;border-bottom:1px solid #333}#pts-mask{position:absolute;display:none;top:0;left:0;height:100%;width:100%;background:#000;z-index:800}#pts-box .pts-close-x{position:relative;top:2px;}#pts-box .tclose{position:absolute;top:10px !important;right:10px !important;width:80px;height:30px;cursor:pointer;font-family:helvetica,sans-serif;font-size:20px}#pts-box .pts-close-waiting{background:url(https://staging.static.points.com/buy/default/buy/images/closespinner.gif) no-repeat 100% 0; text-indent:-5000px; top:15px !important; right: 19px !important;}#pts-box .pts-close-text{font-size:12px;}");
x.styleSheet?x.styleSheet.cssText=y.nodeValue:x.appendChild(y);PTS.debugMode&&(b=l.cssUrl||b);F=[b,l.partnerName,l.cssVersion,I,r];z.id="pts-inline-style";z.setAttribute("type","text/css");z.setAttribute("rel","stylesheet");z.setAttribute("href",F.join("/"));G.appendChild(x);G.appendChild(z);u("loaded")}}catch(C){C.message="Error when executing window.pointsAsyncInit() function: "+C.message,n.handleError(C),t(C)}e.openDialog=function(b){try{b=b||{},v(b),u("open")}catch(c){n.handleError(c,b.errorCallback||
l.errorCallback),t(c),u("/open/error")}};return e}()})(window);